# Site settings
title: Footsies
tagline: The Unofficially Official Foot Cardigan Podcast
owner: Foot Cardigan
podcast_cover: FootsiesPodcast-Cover.png
email: podcast@footsiespodcast.com
description: > # this means to ignore newlines until "baseurl:"
  Footsies is a podcast created by Foot Cardigan co-founders Bryan DeLuca and Matt McClard. Sometimes they talk about making socks and business-y things. Sometimes it might get real weird. One thing is certain: Nothing is certain. Mmmm, deep.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.footsiespodcast.com" # the base hostname & protocol for your site
twitter_username: footsiespodcast
instagram_username: footsiespodcast
facebook_username: footsiespodcast
podcast_rss: /podcast.xml
itunes_url: https://itunes.apple.com/us/podcast/footsies/id978765784

# Build settings
markdown: kramdown
